server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notebook?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root

mybatis:
  mapper-locations: classpath:com.lsc.notebook.mapper/*Mapper.xml
  type-aliases-package: com.lsc.notebook.entity
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#showSql
logging:
  level:
    mapper: DEBUG
